Add reload to S95{platform}

diff --git a/general/package/novatek-osdrv-nt9856x/files/script/S99novatek b/general/package/novatek-osdrv-nt9856x/files/script/S99novatek
--- a/general/package/novatek-osdrv-nt9856x/files/script/S99novatek
+++ b/general/package/novatek-osdrv-nt9856x/files/script/S99novatek
@@ -8,6 +8,21 @@ DAEMON_ARGS="-s"
 # shellcheck source=/dev/null
 [ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"
 
+load_majestic() {
+	printf 'Starting %s: ' "$DAEMON"
+	[ -f /usr/bin/$DAEMON ] || echo -en "DISABLED, "
+	# shellcheck disable=SC2086 # we need the word splitting
+	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/bin/$DAEMON" \
+		-- $DAEMON_ARGS
+	status=$?
+	if [ "$status" -eq 0 ]; then
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
+	return "$status"
+}
+
 # The daemon does not create a pidfile, and use "-m" to instruct start-stop-daemon to create one.
 start() {
 	#logger -s -p daemon.info -t novatek "Check MAC for Novatek devices"
@@ -21,18 +36,7 @@ start() {
 	export TZ=$(cat /etc/TZ)
 	load_novatek -i
 	#
-	printf 'Starting %s: ' "$DAEMON"
-	[ -f /usr/bin/$DAEMON ] || echo -en "DISABLED, "
-	# shellcheck disable=SC2086 # we need the word splitting
-	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/bin/$DAEMON" \
-		-- $DAEMON_ARGS
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return "$status"
+	load_majestic
 }
 
 stop() {
@@ -55,12 +59,13 @@ restart() {
 	start
 }
 
+reload() {
+	load_majestic
+}
+
 case "$1" in
-	start|stop|restart)
+	start|stop|restart|reload)
 		"$1";;
-	reload)
-		# Restart, since there is no true "reload" feature.
-		restart;;
 	*)
 		echo "Usage: $0 {start|stop|restart|reload}"
 		exit 1
