[no ci] Sigmastar: update module script indentation

diff --git a/general/package/sigmastar-osdrv-infinity6b0/files/script/load_sigmastar b/general/package/sigmastar-osdrv-infinity6b0/files/script/load_sigmastar
--- a/general/package/sigmastar-osdrv-infinity6b0/files/script/load_sigmastar
+++ b/general/package/sigmastar-osdrv-infinity6b0/files/script/load_sigmastar
@@ -8,64 +8,61 @@ PATH_SENSOR=${PATH_MODULE}/sensor
 SENSOR=$(fw_printenv -n sensor)
 
 detect_sensor() {
-  devmem 0x1F203C18 16 0x0A80
-  devmem 0x1F207188 16 0x0001
-  devmem 0x1F2608FC 16 0x0003
-  SENSOR=$(ipcinfo -s)
-  fw_setenv sensor ${SENSOR}
+	devmem 0x1F203C18 16 0x0A80
+	devmem 0x1F207188 16 0x0001
+	devmem 0x1F2608FC 16 0x0003
+	SENSOR=$(ipcinfo -s)
+	fw_setenv sensor ${SENSOR}
 }
 
 set_sensor() {
-  case ${SENSOR} in
-    gc4023|gc4653|imx335|os02g10|sc2239|sc223a|sc3335|sc3338)
-      insmod ${PATH_SENSOR}/sensor_${SENSOR}_mipi.ko chmap=1
-      ;;
-    gc2053|gc2083|sc2335)
-      insmod ${PATH_SENSOR}/sensor_${SENSOR}_mipi.ko chmap=1 lane_num=2 hdr_lane_num=2
-      ;;
-    imx307)
-      insmod ${PATH_SENSOR}/sensor_${SENSOR}_mipi.ko chmap=1 lane_num=2 hdr_lane_num=2 mclk=37.125M
-      ;;
-    *)
-      echo -e "\n\e[1;31mUNSUPPORTED sensor - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
-      ;;
-  esac
+	case ${SENSOR} in
+		gc2053|gc2083|gc4023|gc4653|imx307|imx335)
+			insmod ${PATH_SENSOR}/sensor_${SENSOR}_mipi.ko chmap=1
+			;;
+		os02g10|sc2239|sc223a|sc2335|sc3335|sc3338)
+			insmod ${PATH_SENSOR}/sensor_${SENSOR}_mipi.ko chmap=1
+			;;
+		*)
+			echo -e "\n\e[1;31mUNSUPPORTED sensor - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
+			;;
+	esac
 }
 
 insert_ko() {
-  insmod ${PATH_MODULE}/mhal.ko
-  insmod ${PATH_MODULE}/mi_common.ko
-  insmod ${PATH_MODULE}/mi_sys.ko cmdQBufSize=256 logBufSize=256
-  insmod ${PATH_MODULE}/mi_rgn.ko
-  insmod ${PATH_MODULE}/mi_ai.ko
-  insmod ${PATH_MODULE}/mi_ao.ko
-  insmod ${PATH_MODULE}/mi_sensor.ko
-  insmod ${PATH_MODULE}/mi_shadow.ko
-  insmod ${PATH_MODULE}/mi_divp.ko
-  insmod ${PATH_MODULE}/mi_vif.ko
-  insmod ${PATH_MODULE}/mi_vpe.ko
-  insmod ${PATH_MODULE}/mi_venc.ko fw_path=/etc/firmware/chagall.bin
+	insmod ${PATH_MODULE}/mhal.ko
+	insmod ${PATH_MODULE}/mi_common.ko
+	insmod ${PATH_MODULE}/mi_sys.ko cmdQBufSize=256 logBufSize=256
+	insmod ${PATH_MODULE}/mi_rgn.ko
+	insmod ${PATH_MODULE}/mi_ai.ko
+	insmod ${PATH_MODULE}/mi_ao.ko
+	insmod ${PATH_MODULE}/mi_sensor.ko
+	insmod ${PATH_MODULE}/mi_shadow.ko
+	insmod ${PATH_MODULE}/mi_divp.ko
+	insmod ${PATH_MODULE}/mi_vif.ko
+	insmod ${PATH_MODULE}/mi_vpe.ko
+	insmod ${PATH_MODULE}/mi_venc.ko fw_path=/etc/firmware/chagall.bin
 
-  major=$(awk '$2=="mi_poll" {print $1}' /proc/devices)
-  mknod /dev/mi_poll c $major 0
-  echo isproot /etc/firmware > /dev/ispmid
+	major=$(awk '$2=="mi_poll" {print $1}' /proc/devices)
+	mknod /dev/mi_poll c $major 0
+	echo isproot /etc/firmware > /dev/ispmid
 }
 
 if [ ! -e /dev/mi_poll ]; then
-  insert_ko
+	insert_ko
 fi
 
 if [ -z ${SENSOR} ]; then
-  echo -e "\n\e[1;33mAutodetect sensor\e[0m\n" | logger -s -t OpenIPC
-  detect_sensor
+	echo -e "\n\e[1;33mAutodetect sensor\e[0m\n" | logger -s -t OpenIPC
+	detect_sensor
 fi
 
 if [ -z ${SENSOR} ]; then
-  echo -e "\n\e[1;31mSensor parameter MISSING\e[0m\n" | logger -s -t OpenIPC
-  exit 1
+	echo -e "\n\e[1;31mSensor parameter MISSING\e[0m\n" | logger -s -t OpenIPC
+	exit 1
 else
-  echo -e "\n\e[1;32mSensor assigned - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
-  $(lsmod | grep -q ${SENSOR}) || set_sensor
+	echo -e "\n\e[1;32mSensor assigned - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
+	$(lsmod | grep -q ${SENSOR}) || set_sensor
 fi
 
 exit 0
diff --git a/general/package/sigmastar-osdrv-infinity6c/files/script/load_sigmastar b/general/package/sigmastar-osdrv-infinity6c/files/script/load_sigmastar
--- a/general/package/sigmastar-osdrv-infinity6c/files/script/load_sigmastar
+++ b/general/package/sigmastar-osdrv-infinity6c/files/script/load_sigmastar
@@ -8,52 +8,52 @@ PATH_SENSOR=${PATH_MODULE}/sensor
 SENSOR=$(fw_printenv -n sensor)
 
 detect_sensor() {
-  devmem 0x1F2079A8 16 0x0001
-  devmem 0x1F207188 16 0x0000
-  SENSOR=$(ipcinfo -s)
-  fw_setenv sensor ${SENSOR}
+	devmem 0x1F2079A8 16 0x0001
+	devmem 0x1F207188 16 0x0000
+	SENSOR=$(ipcinfo -s)
+	fw_setenv sensor ${SENSOR}
 }
 
 set_sensor() {
-  case ${SENSOR} in
-    sc401ai)
-      insmod ${PATH_SENSOR}/sensor_${SENSOR}_mipi.ko chmap=1
-      ;;
-    *)
-      echo -e "\n\e[1;31mUNSUPPORTED sensor - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
-      ;;
-  esac
+	case ${SENSOR} in
+		sc401ai)
+			insmod ${PATH_SENSOR}/sensor_${SENSOR}_mipi.ko chmap=1
+			;;
+		*)
+			echo -e "\n\e[1;31mUNSUPPORTED sensor - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
+			;;
+	esac
 }
 
 insert_ko() {
-  insmod ${PATH_MODULE}/mi_common.ko g_ModParamPath=${PATH_MODULE}/param.json config_json_path=/${PATH_MODULE}/config.json
-  insmod ${PATH_MODULE}/mi_sys.ko
-  insmod ${PATH_MODULE}/mi_vif.ko
-  insmod ${PATH_MODULE}/mi_sensor.ko
-  insmod ${PATH_MODULE}/mi_isp.ko
-  insmod ${PATH_MODULE}/mi_rgn.ko
-  insmod ${PATH_MODULE}/mi_scl.ko
-  insmod ${PATH_MODULE}/mi_vcodec.ko drv_codec40_common.fw_load_path=/etc/firmware/chagall.bin
-  insmod ${PATH_MODULE}/mi_venc.ko
+	insmod ${PATH_MODULE}/mi_common.ko g_ModParamPath=${PATH_MODULE}/param.json config_json_path=/${PATH_MODULE}/config.json
+	insmod ${PATH_MODULE}/mi_sys.ko
+	insmod ${PATH_MODULE}/mi_vif.ko
+	insmod ${PATH_MODULE}/mi_sensor.ko
+	insmod ${PATH_MODULE}/mi_isp.ko
+	insmod ${PATH_MODULE}/mi_rgn.ko
+	insmod ${PATH_MODULE}/mi_scl.ko
+	insmod ${PATH_MODULE}/mi_vcodec.ko drv_codec40_common.fw_load_path=/etc/firmware/chagall.bin
+	insmod ${PATH_MODULE}/mi_venc.ko
 
-  echo isproot /etc/firmware > /dev/ispmid
+	echo isproot /etc/firmware > /dev/ispmid
 }
 
 if [ ! -e /dev/mi_poll ]; then
-  insert_ko
+	insert_ko
 fi
 
 if [ -z ${SENSOR} ]; then
-  echo -e "\n\e[1;33mAutodetect sensor\e[0m\n" | logger -s -t OpenIPC
-  detect_sensor
+	echo -e "\n\e[1;33mAutodetect sensor\e[0m\n" | logger -s -t OpenIPC
+	detect_sensor
 fi
 
 if [ -z ${SENSOR} ]; then
-  echo -e "\n\e[1;31mSensor parameter MISSING\e[0m\n" | logger -s -t OpenIPC
-  exit 1
+	echo -e "\n\e[1;31mSensor parameter MISSING\e[0m\n" | logger -s -t OpenIPC
+	exit 1
 else
-  echo -e "\n\e[1;32mSensor assigned - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
-  $(lsmod | grep -q ${SENSOR}) || set_sensor
+	echo -e "\n\e[1;32mSensor assigned - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
+	$(lsmod | grep -q ${SENSOR}) || set_sensor
 fi
 
 exit 0
diff --git a/general/package/sigmastar-osdrv-infinity6e/files/script/load_sigmastar b/general/package/sigmastar-osdrv-infinity6e/files/script/load_sigmastar
--- a/general/package/sigmastar-osdrv-infinity6e/files/script/load_sigmastar
+++ b/general/package/sigmastar-osdrv-infinity6e/files/script/load_sigmastar
@@ -8,60 +8,60 @@ PATH_SENSOR=${PATH_MODULE}/sensor
 SENSOR=$(fw_printenv -n sensor)
 
 detect_sensor() {
-  devmem 0x1F2079A4 16 0x0111
-  devmem 0x1F207188 16 0x0001
-  devmem 0x1F2608FC 16 0x0003
-  SENSOR=$(ipcinfo -s)
-  fw_setenv sensor ${SENSOR}
+	devmem 0x1F2079A4 16 0x0111
+	devmem 0x1F207188 16 0x0001
+	devmem 0x1F2608FC 16 0x0003
+	SENSOR=$(ipcinfo -s)
+	fw_setenv sensor ${SENSOR}
 }
 
 set_sensor() {
-  case ${SENSOR} in
-    gc2053|gc4653|imx274|imx335|imx347|imx415|sc8235)
-      insmod ${PATH_SENSOR}/sensor_${SENSOR}_mipi.ko chmap=1
-      ;;
-    *)
-      echo -e "\n\e[1;31mUNSUPPORTED sensor - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
-      ;;
-  esac
+	case ${SENSOR} in
+		gc2053|gc4653|imx274|imx335|imx347|imx415|sc8235)
+			insmod ${PATH_SENSOR}/sensor_${SENSOR}_mipi.ko chmap=1
+			;;
+		*)
+			echo -e "\n\e[1;31mUNSUPPORTED sensor - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
+			;;
+	esac
 }
 
 insert_ko() {
-  insmod ${PATH_MODULE}/mhal.ko
-  insmod ${PATH_MODULE}/mi_common.ko
-  insmod ${PATH_MODULE}/mi_sys.ko cmdQBufSize=768 logBufSize=256
-  insmod ${PATH_MODULE}/mi_rgn.ko
-  insmod ${PATH_MODULE}/mi_ldc.ko
-  insmod ${PATH_MODULE}/mi_ai.ko
-  insmod ${PATH_MODULE}/mi_ao.ko
-  insmod ${PATH_MODULE}/mi_mipitx.ko
-  insmod ${PATH_MODULE}/mi_sensor.ko
-  insmod ${PATH_MODULE}/mi_shadow.ko
-  insmod ${PATH_MODULE}/mi_divp.ko
-  insmod ${PATH_MODULE}/mi_vif.ko
-  insmod ${PATH_MODULE}/mi_vpe.ko
-  insmod ${PATH_MODULE}/mi_venc.ko fw_path=/etc/firmware/chagall.bin
+	insmod ${PATH_MODULE}/mhal.ko
+	insmod ${PATH_MODULE}/mi_common.ko
+	insmod ${PATH_MODULE}/mi_sys.ko cmdQBufSize=768 logBufSize=256
+	insmod ${PATH_MODULE}/mi_rgn.ko
+	insmod ${PATH_MODULE}/mi_ldc.ko
+	insmod ${PATH_MODULE}/mi_ai.ko
+	insmod ${PATH_MODULE}/mi_ao.ko
+	insmod ${PATH_MODULE}/mi_mipitx.ko
+	insmod ${PATH_MODULE}/mi_sensor.ko
+	insmod ${PATH_MODULE}/mi_shadow.ko
+	insmod ${PATH_MODULE}/mi_divp.ko
+	insmod ${PATH_MODULE}/mi_vif.ko
+	insmod ${PATH_MODULE}/mi_vpe.ko
+	insmod ${PATH_MODULE}/mi_venc.ko fw_path=/etc/firmware/chagall.bin
 
-  major=$(awk '$2=="mi_poll" {print $1}' /proc/devices)
-  mknod /dev/mi_poll c $major 0
-  echo isproot /etc/firmware > /dev/ispmid
+	major=$(awk '$2=="mi_poll" {print $1}' /proc/devices)
+	mknod /dev/mi_poll c $major 0
+	echo isproot /etc/firmware > /dev/ispmid
 }
 
 if [ ! -e /dev/mi_poll ]; then
-  insert_ko
+	insert_ko
 fi
 
 if [ -z ${SENSOR} ]; then
-  echo -e "\n\e[1;33mAutodetect sensor\e[0m\n" | logger -s -t OpenIPC
-  detect_sensor
+	echo -e "\n\e[1;33mAutodetect sensor\e[0m\n" | logger -s -t OpenIPC
+	detect_sensor
 fi
 
 if [ -z ${SENSOR} ]; then
-  echo -e "\n\e[1;31mSensor parameter MISSING\e[0m\n" | logger -s -t OpenIPC
-  exit 1
+	echo -e "\n\e[1;31mSensor parameter MISSING\e[0m\n" | logger -s -t OpenIPC
+	exit 1
 else
-  echo -e "\n\e[1;32mSensor assigned - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
-  $(lsmod | grep -q ${SENSOR}) || set_sensor
+	echo -e "\n\e[1;32mSensor assigned - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
+	$(lsmod | grep -q ${SENSOR}) || set_sensor
 fi
 
 exit 0
