Add sensor detect for Gk7205v200

diff --git a/general/package/goke-osdrv-gk7205v200/files/script/load_goke b/general/package/goke-osdrv-gk7205v200/files/script/load_goke
--- a/general/package/goke-osdrv-gk7205v200/files/script/load_goke
+++ b/general/package/goke-osdrv-gk7205v200/files/script/load_goke
@@ -1,18 +1,11 @@
 #!/bin/sh
-# Useage: ./load_goke [ -r|-i|-a ] [ sensor ]
-#         -r : rmmod all modules
-#         -i : insmod all modules
-#    default : rmmod all moules and then insmod them
-# e.g: ./load_goke -i -sensor0 imx307 -osmem 32M
-
-
 ####################Variables Definition##########################
 
 # SoC detect
 CHIP_TYPE=$(ipcinfo --chip_id)
 
 # Memory config
-mem_start=0x40000000        # phy mem start
+mem_start=0x40000000 # phy mem start
 
 mem_total=$(fw_printenv -n totalmem | tr -d 'M')
 mem_total=${mem_total:=64}
@@ -20,16 +13,16 @@ mem_total=${mem_total:=64}
 os_mem_size=$(fw_printenv -n osmem | tr -d 'M')
 os_mem_size=${os_mem_size:=32}
 
-BOARD=demo;
-SNS_TYPE0=imx307;           # sensor type
-YUV_TYPE0=0;                # 0 -- raw, 1 --DC, 2 --bt1120, 3 --bt656
+BOARD=demo
+YUV_TYPE0=0 # 0 -- raw, 1 --DC, 2 --bt1120, 3 --bt656
+
+cd /lib/modules/4.9.37/goke/
 
 ##################################################################
 
 # DDR start:0x40000000, kernel start:0x40000000,  OS(32M); MMZ start:0x42000000
 #
 # echo "${chipid}: ${mem_total}/${os_mem_size} | ${mem_start}/${mmz_start} | ${mmz_size}"
-
 
 # GK7202V300
 #
@@ -39,7 +32,6 @@ YUV_TYPE0=0;                # 0 -- raw, 1 --DC, 2 --bt1120, 3 --bt656
 # mmz_start=0x42000000;         # mmz start addr
 # mmz_size=32M;                 # 32M, mmz size
 
-
 # GK7205V200
 #
 # mem_total=64                  # 64M, total mem
@@ -48,7 +40,6 @@ YUV_TYPE0=0;                # 0 -- raw, 1 --DC, 2 --bt1120, 3 --bt656
 # mmz_start=0x42000000;         # mmz start addr
 # mmz_size=32M;                 # 32M, mmz size
 
-
 # GK7205V300
 #
 # mem_total=128                 # 128M, total mem
@@ -56,7 +47,6 @@ YUV_TYPE0=0;                # 0 -- raw, 1 --DC, 2 --bt1120, 3 --bt656
 # os_mem_size=32                # 32M, os mem
 # mmz_start=0x42000000;         # mmz start addr
 # mmz_size=96M;                 # 96M, mmz size
-
 
 # GK7605V100
 #
@@ -68,14 +58,40 @@ YUV_TYPE0=0;                # 0 -- raw, 1 --DC, 2 --bt1120, 3 --bt656
 
 ##################################################################
 
-report_error()
-{
+report_error() {
 	echo "******* Error: There's something wrong, please check! *****"
 	exit 1
 }
 
-insert_audio()
-{
+insert_osal() {
+	MMZ=$(awk -F '=' '$1=="mmz"{print $2}' RS=" " /proc/cmdline)
+	if [ -z "$MMZ" ]; then
+		insmod osal.ko anony=1 mmz_allocator=gk mmz=anonymous,0,$mmz_start,$mmz_size || report_error
+	else
+		insmod cma_osal.ko anony=1 mmz_allocator=cma mmz=$MMZ || report_error
+	fi
+}
+
+insert_detect() {
+	insmod sysconfig.ko chip=$CHIP_TYPE sensors=unknown g_cmos_yuv_flag=$YUV_TYPE0 board=$BOARD
+	insert_osal
+	insmod gk7205v200_base.ko
+	insmod gk7205v200_isp.ko
+	insmod isp_sensor_i2c.ko
+	insmod isp_sensor_spi.ko
+}
+
+remove_detect() {
+	rmmod -w isp_sensor_spi
+	rmmod -w isp_sensor_i2c
+	rmmod -w gk7205v200_isp
+	rmmod -w gk7205v200_base
+	rmmod -w osal >/dev/null 2>&1
+	rmmod -w cma_osal >/dev/null 2>&1
+	rmmod -w sysconfig
+}
+
+insert_audio() {
 	insmod gk7205v200_aio.ko
 	insmod gk7205v200_ai.ko
 	insmod gk7205v200_ao.ko
@@ -85,8 +101,7 @@ insert_audio()
 	echo "insert audio"
 }
 
-remove_audio()
-{
+remove_audio() {
 	rmmod -w gk7205v200_acodec
 	rmmod -w gk7205v200_adec
 	rmmod -w gk7205v200_aenc
@@ -96,54 +111,48 @@ remove_audio()
 	echo "remove audio"
 }
 
-insert_isp()
-{
+insert_isp() {
 	insmod gk7205v200_isp.ko
 }
 
-insert_sil9024()
-{
+insert_sil9024() {
 	i2c_sel=2
-	if [ "$CHIP_TYPE" == "gk7205v300" ];then
+	if [ "$CHIP_TYPE" == "gk7205v300" ]; then
 		i2c_sel=1
 	fi
 
-	if [ "$BOARD" == "sck" ];then
-		insmod sil9024.ko norm=12 i2c_num=$i2c_sel  #1080P@30fps
+	if [ "$BOARD" == "sck" ]; then
+		insmod sil9024.ko norm=12 i2c_num=$i2c_sel #1080P@30fps
 	fi
 }
 
-insert_adv7179()
-{
+insert_adv7179() {
 	i2c_sel=2
-	if [ "$CHIP_TYPE" == "gk7205v300" ];then
+	if [ "$CHIP_TYPE" == "gk7205v300" ]; then
 		i2c_sel=1
 	fi
 
-	if [ "$BOARD" == "sck" ];then
+	if [ "$BOARD" == "sck" ]; then
 		insmod adv7179.ko norm_mode=0 i2c_num=$i2c_sel # norm_mode = 0:PAL, 1:NTSC
 	fi
 }
 
-insert_isp_piris()
-{
-	if [ "$CHIP_TYPE" == "gk7605v100" -a "$BOARD" == "demo" ];then
+insert_isp_piris() {
+	if [ "$CHIP_TYPE" == "gk7605v100" -a "$BOARD" == "demo" ]; then
 		insmod isp_piris.ko
 	fi
 }
 
-insert_ko()
-{
-	cd /lib/modules/4.9.37/goke/
-	insmod sysconfig.ko chip=$CHIP_TYPE sensors=$SNS_TYPE0 g_cmos_yuv_flag=$YUV_TYPE0 board=$BOARD
-	insmod osal.ko anony=1 mmz_allocator=gk mmz=anonymous,0,$mmz_start,$mmz_size || report_error
+insert_ko() {
+	insmod sysconfig.ko chip=$CHIP_TYPE sensors=$SENSOR g_cmos_yuv_flag=$YUV_TYPE0 board=$BOARD
+	insert_osal
 	insmod gk7205v200_base.ko
 	insmod gk7205v200_sys.ko
 	# insmod gk7205v200_tde.ko
 	insmod gk7205v200_rgn.ko
 	insmod gk7205v200_vgs.ko
 	insmod gk7205v200_vi.ko
-	insert_isp;
+	insert_isp
 	insmod gk7205v200_vpss.ko
 	# insmod gk7205v200_vo.ko                       # unused on OpenIPC
 	# insmod gfbg.ko video="gfbg:vram0_size:1620"   # unused on OpenIPC  # default fb0:D1
@@ -163,12 +172,11 @@ insert_ko()
 	insert_audio
 	insmod mipi_rx.ko
 	# insmod gk7205v200_pm.ko                       # unused on OpenIPC
-        insmod gk7205v200_wdt.ko
+	insmod gk7205v200_wdt.ko
 }
 
-remove_ko()
-{
-        rmmod -w gk7205v200_wdt
+remove_ko() {
+	rmmod -w gk7205v200_wdt
 	# rmmod -w gk7205v200_pm                           # unused on OpenIPC
 	remove_audio
 	rmmod -w mipi_rx
@@ -190,8 +198,8 @@ remove_ko()
 	rmmod -w gk7205v200_vgs
 	rmmod -w gk7205v200_rgn
 	# rmmod -w gk7205v200_tde
-	rmmod -w isp_sensor_i2c &> /dev/null
-	rmmod -w isp_sensor_spi &> /dev/null
+	rmmod -w isp_sensor_i2c &>/dev/null
+	rmmod -w isp_sensor_spi &>/dev/null
 	rmmod -w isp_pwm
 	rmmod -w gk7205v200_sys
 	rmmod -w gk7205v200_base
@@ -199,9 +207,7 @@ remove_ko()
 	rmmod -w sysconfig
 }
 
-
-load_usage()
-{
+load_usage() {
 	echo "Usage:  ./load_goke [-option] [sensor_name]"
 	echo "options:"
 	echo "    -i                       insert modules"
@@ -213,22 +219,21 @@ load_usage()
 	echo -e "for example: ./load_goke -i -sensor imx307 -osmem 32M -board demo -yuv0 0\n"
 }
 
-calc_mmz_info()
-{
-        mmz_start=`echo "$mem_start $os_mem_size"  |
-        awk 'BEGIN { temp = 0; }
+calc_mmz_info() {
+	mmz_start=$(echo "$mem_start $os_mem_size" |
+		awk 'BEGIN { temp = 0; }
         {
                 temp = $1/1024/1024 + $2;
         }
-        END { printf("0x%x00000\n", temp); }'`
+        END { printf("0x%x00000\n", temp); }')
 
-        mmz_size=`echo "$mem_total $os_mem_size"  |
-        awk 'BEGIN { temp = 0; }
+	mmz_size=$(echo "$mem_total $os_mem_size" |
+		awk 'BEGIN { temp = 0; }
         {
                 temp = $1 - $2;
         }
-        END { printf("%dM\n", temp); }'`
-        echo "mmz_start: $mmz_start, mmz_size: $mmz_size"
+        END { printf("%dM\n", temp); }')
+	echo "mmz_start: $mmz_start, mmz_size: $mmz_size"
 }
 
 ######################parse arg###################################
@@ -240,86 +245,105 @@ b_arg_remove=0
 b_arg_os_mem=0
 b_arg_board=0
 
-for arg in $@
-do
-	if [ $b_arg_sensor0 -eq 1 ] ; then
-		b_arg_sensor0=0;
-		SNS_TYPE0=$arg;
+for arg in $@; do
+	if [ $b_arg_sensor0 -eq 1 ]; then
+		b_arg_sensor0=0
+		SENSOR=$arg
 	fi
 
-
-	if [ $b_arg_os_mem -eq 1 ] ; then
-		b_arg_os_mem=0;
-		os_mem_size=$arg;
+	if [ $b_arg_os_mem -eq 1 ]; then
+		b_arg_os_mem=0
+		os_mem_size=$arg
 
 		if [ -z $os_mem_size ]; then
 			echo "[error] os_mem_size is null"
-			exit;
+			exit
 		fi
 	fi
 
-	if [ $b_arg_yuv_type0 -eq 1 ] ; then
-		b_arg_yuv_type0=0;
-		YUV_TYPE0=$arg;
+	if [ $b_arg_yuv_type0 -eq 1 ]; then
+		b_arg_yuv_type0=0
+		YUV_TYPE0=$arg
 	fi
 
-	if [ $b_arg_board -eq 1 ] ; then
-		b_arg_board=0;
-		BOARD=$arg;
+	if [ $b_arg_board -eq 1 ]; then
+		b_arg_board=0
+		BOARD=$arg
 	fi
 
 	case $arg in
-		"-i")
-			b_arg_insmod=1;
-			;;
-		"-r")
-			b_arg_remove=1;
-			;;
-		"-a")
-			b_arg_insmod=1;
-			b_arg_remove=1;
-			;;
-		"-h")
-			load_usage;
-			;;
-		"-sensor0")
-			b_arg_sensor0=1;
-			;;
-		"-sensor")
-			b_arg_sensor0=1;
-			;;
-		"-osmem")
-			b_arg_os_mem=1;
-			;;
-		"-yuv0")
-			b_arg_yuv_type0=1;
-			;;
-		"-board")
-			b_arg_board=1;
-			;;
+	"-i")
+		b_arg_insmod=1
+		;;
+	"-r")
+		b_arg_remove=1
+		;;
+	"-a")
+		b_arg_insmod=1
+		b_arg_remove=1
+		;;
+	"-h")
+		load_usage
+		;;
+	"-sensor0")
+		b_arg_sensor0=1
+		;;
+	"-sensor")
+		b_arg_sensor0=1
+		;;
+	"-osmem")
+		b_arg_os_mem=1
+		;;
+	"-yuv0")
+		b_arg_yuv_type0=1
+		;;
+	"-board")
+		b_arg_board=1
+		;;
 	esac
 done
 #######################parse arg end########################
-if [ $os_mem_size -ge $mem_total ] ; then
+if [ $os_mem_size -ge $mem_total ]; then
 	echo "[err] os_mem[$os_mem_size], over total_mem[$mem_total]"
-	exit;
+	exit
 fi
 
-calc_mmz_info;
+calc_mmz_info
 
 #######################Action###############################
 
 if [ $# -lt 1 ]; then
-    load_usage;
-    exit 0;
-fi
-
-
-if [ $b_arg_remove -eq 1 ]; then
-	remove_ko;
+	load_usage
+	exit 0
 fi
 
 if [ $b_arg_insmod -eq 1 ]; then
-	insert_ko;
+	if [ -n "$SENSOR" ]; then
+		logger -s -p daemon.info -t goke "SENSOR: ${SENSOR}"
+	else
+		if fw_printenv -n sensor >/dev/null; then
+			export SENSOR=$(fw_printenv -n sensor)
+			logger -s -p daemon.info -t goke "Get data from U-Boot ENV and set SENSOR as ${SENSOR}"
+		else
+			insert_detect
+			SENSOR_DETECT=$(ipcinfo --short-sensor)
+			export SENSOR=${SENSOR_DETECT:=unknown}
+			remove_detect
+			logger -s -p daemon.info -t goke "Get data from ipcinfo and set SENSOR as ${SENSOR}"
+			fw_setenv sensor $SENSOR && logger -s -p daemon.info -t goke "Writing ${SENSOR} to U-Boot ENV"
+		fi
+	fi
 fi
 
+if [ $b_arg_remove -eq 1 ]; then
+	remove_ko
+fi
+
+if [ "$SENSOR" = "unknown" ]; then
+	logger -s -p daemon.err -t goke "SENSOR is not detected, aborting..."
+	exit 1
+else
+	if [ $b_arg_insmod -eq 1 ]; then
+		insert_ko
+	fi
+fi
