[no ci] Overlay: update sysupgrade and scripts

diff --git a/general/package/majestic/files/S95majestic b/general/package/majestic/files/S95majestic
--- a/general/package/majestic/files/S95majestic
+++ b/general/package/majestic/files/S95majestic
@@ -41,8 +41,20 @@ stop() {
 	fi
 }
 
+pause() {
+	printf "Pausing $DAEMON: "
+	start-stop-daemon -K -s QUIT -q -p "$PIDFILE"
+	status=$?
+	if [ "$status" -eq 0 ]; then
+		rm -f "$PIDFILE"
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
+}
+
 case "$1" in
-	start|stop)
+	start|stop|pause)
 		"$1"
 		;;
 
