majestic: fix reload signal and start status for watchdog-friendly init

diff --git a/general/package/majestic/files/S95majestic b/general/package/majestic/files/S95majestic
--- a/general/package/majestic/files/S95majestic
+++ b/general/package/majestic/files/S95majestic
@@ -6,21 +6,24 @@ DAEMON_ARGS="-s"
 start() {
 	echo -n "Starting $DAEMON: "
 	start-stop-daemon -b -S -q -x "$DAEMON" -- $DAEMON_ARGS
-	if [ $? -eq 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL (already running)"
-	fi
+	case $? in
+		0) echo "OK" ;;
+		1) echo "FAIL (already running)" ;;
+		*) echo "FAIL" ;;
+	esac
 }
 
 stop() {
 	echo -n "Stopping $DAEMON: "
-	start-stop-daemon -K -q -x "$DAEMON"
-	if [ $? -eq 0 ]; then
+	if start-stop-daemon -K -q -x "$DAEMON"; then
 		echo "OK"
 	else
 		echo "FAIL"
 	fi
+}
+
+reload() {
+	start-stop-daemon -K -s 1 -q -x "$DAEMON"
 }
 
 case "$1" in
@@ -35,7 +38,7 @@ case "$1" in
 		;;
 
 	reload)
-		killall -1 "$DAEMON"
+		reload
 		;;
 
 	*)
