Overlay: sync init.d script structure (#1369)

diff --git a/general/overlay/etc/init.d/S21rngd b/general/overlay/etc/init.d/S21rngd
--- a/general/overlay/etc/init.d/S21rngd
+++ b/general/overlay/etc/init.d/S21rngd
@@ -1,21 +1,27 @@
 #!/bin/sh
 
 DAEMON="rngd"
-DAEMON_ARGS="-r /dev/urandom"
-PID_FILE="/var/run/$DAEMON.pid"
+PIDFILE="/var/run/$DAEMON.pid"
+RNGD_ARGS="-r /dev/urandom"
 
 start() {
-	echo "Starting $DAEMON..."
-	start-stop-daemon -S -q -x "/usr/sbin/$DAEMON" -- $DAEMON_ARGS
+	printf "Starting $DAEMON: "
+	start-stop-daemon -S -q -x "/usr/sbin/$DAEMON" -- $RNGD_ARGS
+	if [ $? = 0 ]; then
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
 }
 
 stop() {
-	echo "Stopping $DAEMON..."
-	# This daemon does not exit properly with the default TERM signal unless
-	# it's forced to work by something reading /dev/random. Killing it and
-	# removing its PID file is more straightforward.
-	start-stop-daemon -K -q -s KILL -p "$PID_FILE" -n "$DAEMON"
-	rm -f "$PID_FILE"
+	printf "Stopping $DAEMON: "
+	start-stop-daemon -K -q -n "$DAEMON"
+	if [ $? = 0 ]; then
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
 }
 
 case "$1" in
@@ -25,11 +31,12 @@ case "$1" in
 
 	restart|reload)
 		stop
+		sleep 1
 		start
 		;;
 
 	*)
-		echo "Usage: $0 {start|stop|restart|reload}" >&2
+		echo "Usage: $0 {start|stop|restart|reload}"
 		exit 1
 		;;
 esac
