[no ci] S99watchdog: enhance boot messages

diff --git a/general/overlay/etc/init.d/S99watchdog b/general/overlay/etc/init.d/S99watchdog
--- a/general/overlay/etc/init.d/S99watchdog
+++ b/general/overlay/etc/init.d/S99watchdog
@@ -18,12 +18,22 @@ vendor_supported() {
 
 start()
 {
-	if vendor_supported && [ "$(cli -g .watchdog.enabled)" = "false" ] && [ "$WATCHDOG_ENABLED" = "true" ]; then
+	if [ "$(cli -g .watchdog.enabled)" = "true" ]; then
 		printf "Starting ${DAEMON}: "
-		start-stop-daemon -S -q -x "/sbin/${DAEMON}" -- ${WATCHDOG_ARGS}
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		echo "majestic watchdog enabled"
+		exit 0
+	fi
+
+	if vendor_supported && [ "$WATCHDOG_ENABLED" = "true" ]; then
+		printf "Starting ${DAEMON}: "
+		start-stop-daemon -b -S -q -x "/sbin/${DAEMON}" -- ${WATCHDOG_ARGS}
+		if [ $? = 0 ]; then
+			echo "OK"
+		else
+			echo "FAIL"
+		fi
 	else
-		echo "Watchdog: System watchdog disabled, unsupported vendor or Majestic Watchdog enabled"
+		echo "Watchdog: System watchdog disabled"
 		exit 0
 	fi
 }
