Update sysupgrade script

diff --git a/general/overlay/usr/sbin/sysupgrade b/general/overlay/usr/sbin/sysupgrade
--- a/general/overlay/usr/sbin/sysupgrade
+++ b/general/overlay/usr/sbin/sysupgrade
@@ -74,16 +74,30 @@ download_firmware() {
 	echo "Download from $url"
 	[ -z "$HASERLVER" ] && progress="-#" || progress="-s"
 	[ "$(curl -o /dev/null -s -w '%{http_code}\n' "$url")" = "000" ] && die "Check your network!"
-	curl --connect-timeout 30 -m 60 -L "$url" ${progress} -o - | gzip -d | tar xf - -C /tmp || die "Cannot retrieve $url"
+	curl --connect-timeout 30 -s -m 60 -L "$url" ${progress} -o - | gzip -d | tar xf - -C /tmp && echo_c 32 "Received and unpacked" || die "Cannot retrieve $url"
 	if [ "$skip_md5" -eq 0 ]; then
 		(cd /tmp && md5sum -s -c *.md5sum) || die "Wrong checksum!"
 	fi
 }
 
 free_resources() {
-	echo_c 97 "\nStop services, unload modules"
-	killall majestic crond klogd ntpd rngd syslogd >/dev/null 2>&1 || true
-	"load_$vendor" -r >/dev/null 2>&1 || true
+	# echo_c 97 "\nStop services, unload modules"
+	# killall majestic crond klogd ntpd rngd syslogd >/dev/null 2>&1 || true
+	# "load_$vendor" -r >/dev/null 2>&1 || true
+	#
+	echo_c 97 "\nStop services, sync and fresh memory"
+	for proc in majestic crond klogd ntpd rngd syslogd
+	do
+		echo -n "Killing $proc "
+		while [ -n "$(pidof $proc)" ]
+		do
+			killall $proc >/dev/null 2>&1 || true
+			sleep 0.1
+			echo -n "."
+		done
+		echo ". OK"
+	done
+	sync; echo 3 > /proc/sys/vm/drop_caches
 }
 
 get_device() {
