add tftp support
Signed-off-by: Conke Hu <conke.hu@maxwit.com>

diff --git a/general/overlay/usr/sbin/sysupgrade b/general/overlay/usr/sbin/sysupgrade
--- a/general/overlay/usr/sbin/sysupgrade
+++ b/general/overlay/usr/sbin/sysupgrade
@@ -216,10 +216,16 @@ download_firmware() {
 			echo "Resolved $build_id for $platform"
 		fi
 		[ -z "$url" ] && url=$(fw_printenv -n upgrade || echo "https://github.com/OpenIPC/${repo:-builder}/releases/download/latest/openipc.$build.tgz")
-		[ "${url%\.tgz}.tgz" != "$url" ] && url="${url}/openipc.$build.tgz"
 		echo "Download from $url"
-		[ "$(curl -o /dev/null -s -k -w '%{http_code}\n' "$url")" = "000" ] && die "Check your network!"
-		curl --connect-timeout 30 -s -k -m 120 -L "$url" -s -o - | gzip -d | tar xf - -C /tmp && echo_c 32 "Received and unpacked" || die "Cannot retrieve $url"
+		if [ "${url}" == tftp ]; then
+			tftp -g -l /tmp/openipc.$build.tgz -r openipc.$build.tgz $(fw_printenv -n serverip)
+			tar xf /tmp/openipc.$build.tgz -C /tmp
+			rm /tmp/openipc.$build.tgz
+		else
+			[ "${url%\.tgz}.tgz" != "$url" ] && url="${url}/openipc.$build.tgz"
+			[ "$(curl -o /dev/null -s -k -w '%{http_code}\n' "$url")" = "000" ] && die "Check your network!"
+			curl --connect-timeout 30 -s -k -m 120 -L "$url" -s -o - | gzip -d | tar xf - -C /tmp && echo_c 32 "Received and unpacked" || die "Cannot retrieve $url"
+		fi
 	fi
 	if [ "1" != "$skip_md5" ]; then
 		(cd /tmp && md5sum -s -c *.md5sum) || die "Wrong checksum!"
