Applied the review suggestions, using a 60-second maximum retry delay and a 3-second DNS timeout to better tolerate slower networks.

diff --git a/general/overlay/usr/sbin/wireguard b/general/overlay/usr/sbin/wireguard
--- a/general/overlay/usr/sbin/wireguard
+++ b/general/overlay/usr/sbin/wireguard
@@ -3,7 +3,7 @@
 config_path="/tmp/wireguard.conf"
 delay_start=0
 delay_step=10
-delay_max=300
+delay_max=60
 
 . /usr/sbin/common
 
@@ -24,7 +24,7 @@ start() {
 	prog="${0##*/}[$subshell_pid]"
 
 	echo "$host" | grep -qE '^\[|^((^|\.)(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])){4}$' ||
-		nslookup "$host" >/dev/null 2>&1 || {
+		nslookup -timeout=3 -retry=1 "$host" >/dev/null 2>&1 || {
 			warning "Unable to resolve the WireGuard server hostname"
 			return 1
 		}
@@ -79,5 +79,6 @@ if ! start; then
 		done
 	} &
 
+	# 255 indicates that startup was deferred to the background retry loop.
 	exit 255
 fi
