[no ci] Sigmastar: add sensor autodetection

diff --git a/general/package/sigmastar-osdrv-infinity6e/files/script/load_sigmastar b/general/package/sigmastar-osdrv-infinity6e/files/script/load_sigmastar
--- a/general/package/sigmastar-osdrv-infinity6e/files/script/load_sigmastar
+++ b/general/package/sigmastar-osdrv-infinity6e/files/script/load_sigmastar
@@ -5,9 +5,27 @@
 
 PATH_MODULE=/lib/modules/4.9.84/sigmastar
 PATH_FIRMWARE=/etc/sensors/venc_fw/chagall.bin
-
-# Sensor
 SENSOR=$(fw_printenv -n sensor)
+
+detect_sensor() {
+  insmod ${PATH_MODULE}/sensor_rx_mipi.ko chmap=1
+  SENSOR=$(majestic | awk '/Autodetect/ {print $NF}')
+  rmmod drv_ms_cus_RX_MIPI
+  fw_setenv sensor ${SENSOR}
+}
+
+set_sensor() {
+  $(lsmod | grep -q ${SENSOR}) && rmmod drv_ms_cus_${SENSOR}_MIPI
+
+  case $SENSOR in
+    imx274|imx335|imx347|imx415|sc8235)
+      insmod ${PATH_MODULE}/sensor_${SENSOR}_mipi.ko chmap=1
+      ;;
+    *)
+      echo -e "\n\e[1;31mUNSUPPORTED sensor found - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
+      ;;
+  esac
+}
 
 insert_ko() {
   insmod ${PATH_MODULE}/mhal.ko
@@ -24,7 +42,6 @@ insert_ko() {
   insmod ${PATH_MODULE}/mi_vif.ko
   insmod ${PATH_MODULE}/mi_vpe.ko
   insmod ${PATH_MODULE}/mi_venc.ko fw_path=${PATH_FIRMWARE}
-  insmod ${PATH_MODULE}/sensor_${SENSOR}_mipi.ko chmap=1
 
   major=$(awk '$2=="mi_poll" {print $1}' /proc/devices)
   mknod /dev/mi_poll c $major 0
@@ -33,16 +50,21 @@ insert_ko() {
   mdev -s
 }
 
-if [ -z ${SENSOR} ]; then
-  echo -e "\n\e[1;31mThe sensor parameter is MISSING\e[0m\n" | logger -s -t OpenIPC
-  echo -e "\n\e[1;33mUsage: fw_setenv sensor [SENSOR]\e[0m\n" | logger -s -t OpenIPC
-  exit 1
-else
-  echo -e "\n\e[1;32mThe sensor is assigned - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
-fi
-
 if [ ! -e /dev/mi_poll ]; then
   insert_ko
+fi
+
+if [ -z ${SENSOR} ]; then
+  echo -e "\n\e[1;33mAutodetect sensor\e[0m\n" | logger -s -t OpenIPC
+  detect_sensor
+fi
+
+if [ -z ${SENSOR} ]; then
+  echo -e "\n\e[1;31mSensor parameter is MISSING\e[0m\n" | logger -s -t OpenIPC
+  exit 1
+else
+  echo -e "\n\e[1;32mSensor is assigned - ${SENSOR}\e[0m\n" | logger -s -t OpenIPC
+  set_sensor
 fi
 
 exit 0
